project_id = "hokieadvisor"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "hokieadvisor://auth/callback"
additional_redirect_urls = ["hokieadvisor://auth/callback"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[storage]
enabled = true
file_size_limit = "12MiB"

[functions.chat]
enabled = true
verify_jwt = false
import_map = "./functions/chat/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/chat/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/chat/*.html" ]

[functions.account]
enabled = true
verify_jwt = false
entrypoint = "./functions/account/index.ts"

[functions.transcript]
enabled = true
verify_jwt = false
entrypoint = "./functions/transcript/index.ts"

[functions.dars]
enabled = true
verify_jwt = false
entrypoint = "./functions/dars/index.ts"

[functions.audit]
enabled = true
verify_jwt = false
entrypoint = "./functions/audit/index.ts"

[functions.tutoring]
enabled = true
verify_jwt = false
entrypoint = "./functions/tutoring/index.ts"
